import Head from "next/head";
import { PrimaryButton, SecondaryButton } from "../components/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Hello Next.js</p>
        <p className="description">This is a simple example of a Next.js App</p>

        <div className="space-x-4 ml-2">
          <SecondaryButton size="small"> cool</SecondaryButton>
          <PrimaryButton size="medium">cool</PrimaryButton>
        </div>
      </main>
    </div>
  );
}
